print("HAPPY-LIBS #1")
print("~~~~~~~~~~~~~~~~~~~~")
print("Today, we're  going to be making a story!")
input("Press 'Enter' when you're ready.")

print(" ")
print("~~~~~~~~~~~~~~~~~~~~")
print(" ")
household_object = input("What's a common household object? ")
number_1 = input("What's a number between 1-10? ")
number_2 = input("What's another number, between 1-5? ")
print(" ")
color = input("What's your favorite color? ")
sport = input("What's your favorite sport? ")
language = input("Give me a common language. ")