print(" ")
print(r" ___   ___   ___   ___   ___   ___   ___   ___   ___   ___   ")
print(r"(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)  ")
print(r"    (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)      ")
print(" ")

print(r" _    _ _____ _     _____ ________  ___ _____   _____ _____   _   _   ___  ______________   __     _     ___________  _____ ")
print(r"| |  | |  ___| |   /  __ \  _  |  \/  ||  ___| |_   _|  _  | | | | | / _ \ | ___ \ ___ \ \ / /    | |   |_   _| ___ \/  ___|")
print(r"| |  | | |__ | |   | /  \/ | | | .  . || |__     | | | | | | | |_| |/ /_\ \| |_/ / |_/ /\ V /_____| |     | | | |_/ /\ `--. ")
print(r"| |/\| |  __|| |   | |   | | | | |\/| ||  __|    | | | | | | |  _  ||  _  ||  __/|  __/  \ /______| |     | | | ___ \ `--. \ ")
print(r"\  /\  / |___| |___| \__/\ \_/ / |  | || |___    | | \ \_/ / | | | || | | || |   | |     | |      | |_____| |_| |_/ //\__/ /")
print(r" \/  \/\____/\_____/\____/\___/\_|  |_/\____/    \_/  \___/  \_| |_/\_| |_/\_|   \_|     \_/      \_____/\___/\____/ \____/ ")
                                                                                                                            
                                                                                                                            
print(" ")
print(r" ___   ___   ___   ___   ___   ___   ___   ___   ___   ___   ")
print(r"(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)  ")
print(r"    (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)      ")
print(" ")
print("Today, we're  going to be making a story!")
input("Press 'Enter' when you're ready.")

print(" ")
print(r" ___   ___   ___   ___   ___   ___   ___   ___   ___   ___   ")
print(r"(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)  ")
print(r"    (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)      ")
print(" ")
household_object = input("What's a common household object? ")
number_1 = input("What's a number between 3-10 [NO DECIMALS]? ")
number_2 = input("What's another number, between 1-3 [NO DECIMALS]? ")

print(" ")

color = input("What's your favorite color? ")
sport_ball = input("What's your favorite sport ball [ex. soccer ball]? ")
language = input("Give me a common language. ")

print(" ")
print("Almost done!")
print(" ")

common_pet = input("What's a common pet? ")
adjective = input("Now, what's an adjective (word that describes things)? ")
word = input("Favorite way to say 'yayy!!!' . ")

print(" ")
print("Awesome! You've finished your part in making our story!")
input("Now, with the words you've chosen, you can enjoy a good laugh!")
print(" ")
print(r" ___   ___   ___   ___   ___   ___   ___   ___   ___   ___   ")
print(r"(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)  ")
print(r"    (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)      ")
print(" ")

print(f"You want to play a game, but you can't seem to find your {sport_ball}.")
print(f"Instead of playing with your lost {sport_ball}, you decide to make up your own game.")
input(" ")
print(f"You find an old {household_object}. Its quite {adjective}.")
input(" ")
print(f"You've decided a few rules like how people can only wear {color} clothing while playing.")
print(f"As well as how many can play, {number_1} maximum and {number_2} minimum.")
input(" ")
print(f"Additionally, if theres a {common_pet} in the house, they can join in on the fun!")
input(f"If players want an extra challenge, they can only speak {language} while playing the game!")
print(f"Lastly, if you score a point everyone on your team yells '{word}'!!")

input(" ")

name = input("What an awesome story!! What would you like to name your new game? ")
print(f"{name}")
input("I like it!!")

print(" ")
print(r" ___   ___   ___   ___   ___   ___   ___   ___   ___   ___   ")
print(r"(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)_(___)  ")
print(r"    (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)   (_)      ")
print(" ")

print(r" ███████████ █████                           █████         █████ █████                     ███")
print(r"▒█▒▒▒███▒▒▒█▒▒███                           ▒▒███         ▒▒███ ▒▒███                     ▒███")
print(r"▒   ▒███  ▒  ▒███████    ██████   ████████   ▒███ █████    ▒▒███ ███    ██████  █████ ████▒███")
print(r"    ▒███     ▒███▒▒███  ▒▒▒▒▒███ ▒▒███▒▒███  ▒███▒▒███      ▒▒█████    ███▒▒███▒▒███ ▒███ ▒███")
print(r"    ▒███     ▒███ ▒███   ███████  ▒███ ▒███  ▒██████▒        ▒▒███    ▒███ ▒███ ▒███ ▒███ ▒███")
print(r"    ▒███     ▒███ ▒███  ███▒▒███  ▒███ ▒███  ▒███▒▒███        ▒███    ▒███ ▒███ ▒███ ▒███ ▒▒▒ ")
print(r"    █████    ████ █████▒▒████████ ████ █████ ████ █████       █████   ▒▒██████  ▒▒████████ ███")
print(r"  ▒▒▒▒▒    ▒▒▒▒ ▒▒▒▒▒  ▒▒▒▒▒▒▒▒ ▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒ ▒▒▒▒▒       ▒▒▒▒▒     ▒▒▒▒▒▒    ▒▒▒▒▒▒▒▒ ▒▒▒ ")
                                                                                              
print(r"                                                        -onionbe [Maya]")
                                                                                                                                                                                          